import 'package:flutter/material.dart';

class NosotrosScreenPage extends StatefulWidget {
  NosotrosScreenPage({Key key}) : super(key: key);

  @override
  _NosotrosScreenPageState createState() => _NosotrosScreenPageState();
}

class _NosotrosScreenPageState extends State<NosotrosScreenPage> with SingleTickerProviderStateMixin{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Color(0xFFFFFFFF),
        appBar: AppBar(
          automaticallyImplyLeading: true,
          title: Text('Quienes Somos'),
          backgroundColor: Color(0xFF6ca125),
          leading: IconButton(icon:Icon(Icons.arrow_back),
            onPressed:() => Navigator.pop(context, false))),
        body: Column(
          children: <Widget>[
            Container(
              padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
              child: Image.asset('assets/images/logo3.jpg', width: 300.0, alignment: Alignment.topCenter),
            ),
            SizedBox(height: 10.0),
            Container(
              height: MediaQuery.of(context).size.height-300,
              padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 5.0),
              child: SingleChildScrollView(
                child: Column(
                  children: _propuesta(),
                ),
              ),
            )
          ],
        )
      )
    );
  }

  List<Widget> _propuesta() => <Widget>[
    Text('Misión', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 10.0),
    Text('Agrupar y representar a los asociados ante la sociedad y autoridades, generando servicios de valor y calidad que permitan el desarrollo de los Auditores y Contadores Públicos Autorizados, para fortalecerlos en su desarrollo humano y profesional, dentro de los más altos estándares éticos, en beneficio de la sociedad.'),
    SizedBox(height: 5.0),
    Text('Contando con un equipo de trabajo competente y cumpliendo con los principios éticos y de responsabilidad social.'),
    SizedBox(height: 10.0),
    Text('Visión', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 10.0),
    Text('Ser la comunidad de profesionales Auditores y Contadores Públicos Autorizados más prestigiosa, para contribuir y brindar servicios de valor y calidad que contribuyan al desarrollo de la competitividad dentro la sociedad.'),
    SizedBox(height: 10.0),
    Text('Quienes Somos', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 10.0),
    Text('Somos un frente joven que tiene los siguientes principios y valores para su actuar:'),
    SizedBox(height: 5.0),
    Text('Verdad. La esencia del trabajo del Auditor y Contador Público Autorizado radica en la verdad. Es su razón de ser. La verdad, aun en la más difícil de las situaciones, es liberadora. La verdad hace la vida.'),
    SizedBox(height: 5.0),
    Text('Debemos mantener, ante todo, la verdad: la verdad en nue stras acciones, la verdad en nuestro trabajo, la verdad en la información que presentamos, porque la verdad es el vínculo que nos acerca a nuestros asociados, a nuestros clientes, a nuestros proveedores, a nuestro personal y a la sociedad misma.'),
    SizedBox(height: 5.0),
    Text('Integridad. Integridad es probidad, es rectitud, es honestidad y es respeto. Debemos ser íntegros y leales para obtener de la sociedad la confianza y la credibilidad, indispensables para el sustento de las relaciones personales, profesionales y comerciales. La integridad va de la mano con la ética personal y profesional.'),
    SizedBox(height: 5.0),
    Text('La integridad es la congruencia de nuestros valores con las prácticas de nuestra institución.'),
    SizedBox(height: 5.0),
    Text('Responsabilidad. Ser responsables es tener la capacidad de reconocer el alcance de nuestras acciones y de sus consecuencias, y de responder por ellas.'),
    SizedBox(height: 5.0),
    Text('En nuestra profesión, la responsabilidad es factor sustantivo para alcanzar el éxito. Debemos ser responsables y disciplinados en todas las acciones que desarrolla nuestra institución y en el impacto que pueden causar en las disciplinas que son inherentes a nuestra profesión, no sólo a nuestros asociados, clientes, proveedores y personal, sino a toda nuestra sociedad.'),
    SizedBox(height: 5.0),
    Text('Compromiso. El compromiso comprende el deber de mantener una actitud de apertura para escuchar las críticas y sugerencias recibidas de nuestros asociados, clientes, proveedores, personal y comunidad en general, y de actuar en consecuencia.'),
    SizedBox(height: 5.0),
    Text('Comprometerse es obligarse, con libertad, a actuar, a responder, a cooperar, a ser responsable.'),
    SizedBox(height: 5.0),
    Text('Nuestro compromiso comprende también una actitud de diálogo y de inclusión, aun para quienes no comparten nuestras ideas y nuestros ideales, porque conformamos un grupo de aprendizaje, deseoso de crear y de innovar.'),
    SizedBox(height: 5.0),
    Text('Nuestro compromiso es, en resumen, dar lo mejor de nosotros mismos a todos aquellos que se relacionan con nuestra institución.'),
    SizedBox(height: 5.0),
    Text('Lealtad a las personas: Ofrecemos un ambiente de respeto, calidez y equidad.'),
    SizedBox(height: 5.0),
    Text('Atención de excelencia: Trabajamos en equipo con un enfoque de servicio de valor, tomando en cuenta los detalles.'),
    SizedBox(height: 5.0),
    Text('Actuación íntegra y honesta: Nos comprometemos a ser congruentes entre lo que decimos y hacemos, predicando con el ejemplo.'),
    SizedBox(height: 5.0),
    Text('Fortalecimiento del CAULP: Fomentamos la ética, el conocimiento, la innovación y el liderazgo.'),
    SizedBox(height: 5.0),
    Text('Permanencia en el tiempo: Somos sensibles al cambio y respondemos en forma organizada cumpliendo nuestra misión día a día.'),
    SizedBox(height: 5.0),
    Text('Contamos con Política de Calidad para: Contar con un equipo de trabajo enfocado a la agrupación y desarrollo de los Auditores y Contadores Públicos Autorizados, para representar y fortalecer a la profesión, mediante servicios de calidad y la mejora continua, superando sus expectativas y necesidades; Acorde a lo que ofrecemos (Plan de Trabajo).'),
    SizedBox(height: 5.0),
    Text('Objetivos de Calidad: Desarrollar servicios de valor que coadyuven a la competitividad de los profesionales registrados al CAULP. Consolidar el crecimiento sostenido del registro al Colegio y su sustentabilidad.'),
    SizedBox(height: 10.0),
    Text('Que Ofrecemos', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 10.0),
    Text('Los integrantes del Frente GEMA, queremos compartir las alternativas detalladas a continuación para poder abordar una transformación de tal magnitud que nos colocara en un sitial preferencial dentro nuestra sociedad y contribuirá con el desarrollo de nuestro país.'),
    SizedBox(height: 5.0),
    Text('En una era de transformación e innovación, apostamos por el desarrollo profesional y personal de nuestros asociados que serán los líderes del futuro. Para lograr estos objetivos, nuestras propuestas son:'),
    SizedBox(height: 5.0),
    Text('Conocimiento, Experiencia y Juventud', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('1. Actualización de información del registro de los Asociados, para tener certeza absoluta sobre el status de los asociados en cuanto a cuotas.'),
    SizedBox(height: 10.0),
    Text('2. Análisis y determinación del Status de los Asociados con cuotas pendientes de pago.'),
    SizedBox(height: 5.0),
    Text('3. Difundir el Estatuto Orgánico y Reglamento del CAULP edición Mayo 1996 para conocimiento del Asociado.'),
    SizedBox(height: 5.0),
    Text('4. Convocar a Asamblea Extraordinaria para la modificación del Estatuto Orgánico y Reglamento del CAULP edición Mayo 1996.'),
    SizedBox(height: 5.0),
    Text('5. Poner en consideración de la Asamblea Extraordinaria sobre el reconocimiento y procedimiento sobre las categorías de Asociados (Fundadores, Honorarios, Activos y Eventuales).'),
    SizedBox(height: 10.0),
    Text('6. Atención personalizada al asociado.'),
    SizedBox(height: 5.0),
    Text('7. Incentivo a la inscripción de nuevos asociados al CAULP.'),
    SizedBox(height: 5.0),
    Text('8. Apertura de oficinas de atención Profesional a la sociedad paceña, que este conformada por miembros del Consejo Técnico Departamental de Auditoria y Contabilidad y Asociados voluntarios como parte de la Responsabilidad Social del CAULP.'),
    SizedBox(height: 5.0),
    Text('9. Biblioteca especializada para consulta de los asociados.'),
    SizedBox(height: 10.0),
    Text('Ética con valores y Transparencia', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('1. Actuar ético de todos los miembros del Directorio del Frente gEMA, en cumplimiento a los Estatutos y Reglamentos vigentes y modificados del CAULP.'),
    SizedBox(height: 5.0),
    Text('2. Reglamentar la Rendición de Ingresos percibidos por concepto de cobranzas de cuotas y otros conceptos.'),
    SizedBox(height: 5.0),
    Text('3. Reglamentar Rendición de Cuentas por presupuestos aprobados por el Directorio.'),
    SizedBox(height: 5.0),
    Text('4. Apoyo para la Defensa Profesional de los Asociados, previa valoración ética y legal de cada caso.'),
    SizedBox(height: 5.0),
    Text('5. Presentación semestral del Informe Económico, Financiero y Laboral a los Asociados en Asamblea Ordinaria.'),
    SizedBox(height: 5.0),
    Text('6. Publicación del Informe Económico Financiero y Laboral en redes sociales.'),
    SizedBox(height: 5.0),
    Text('Capacitación e Investigación', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('1. Con el objetivo de una capacitación acorde a las exigencias del mercado laboral, serán realizadas por facilitadores reconocidos tanto nacionales como internacionales.'),
    SizedBox(height: 5.0),
    Text('2. Se implementara la capacitación en línea en tiempo real conjuntamente la presencial que tendrá el mismo valor de Certificación y Acreditación'),
    SizedBox(height: 5.0),
    Text('3. A los asociados que cumplan las 20 horas de capacitación continua como mínimo, se emitirá el Certificado de Acreditación por capacitación que tendrá valor curricular'),
    SizedBox(height: 5.0),
    Text('4. Asignar el Presupuesto de investigación profesional para promover y destacar a los mejores asociados del CAULP, como premio a la investigación se pondrá en consideración la mejor investigación a la AIC para su correspondiente exposición y se promocionara en la edición de Boletines tanto impresos como digitales.'),
    SizedBox(height: 5.0),
    Text('5. Promover ferias de apoyo al talento intelectual y de emprendimiento.'),
    SizedBox(height: 5.0),
    Text('6. Promover foros y mesas de discusión sobre temas coyunturales que atingen a la profesión.'),
    SizedBox(height: 5.0),
    Text('Tecnología e Innovación', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('Tecnología:', style: TextStyle(fontWeight: FontWeight.bold)),
    Text('Tecnología: Los asociados podrán identificar, disminuir o evitar riesgos en sus actividades profesionales como Auditores, a través de la adopción de la tecnología que esté acorde a las exigencias del mercado.'),
    SizedBox(height: 5.0),
    Text('Todos los asociados deben ver el manejo del riesgo digital como una fuente de ventaja competitiva.'),
    SizedBox(height: 5.0),
    Text('Digitalización de los Files de los Asociados, para una identificación oportuna de la sociedad de los profesionales registrados al CAULP.'),
    SizedBox(height: 5.0),
    Text('Innovación:', style: TextStyle(fontWeight: FontWeight.bold)),
    Text('Cobros por depósitos y/o transferencias Bancarias.'),
    SizedBox(height: 5.0),
    Text('Capacitación en Línea en tiempo real con profesionales nacionales e internacionales.'),
    SizedBox(height: 5.0),
    Text('Videoteca, que ofrecerá en línea, los mejores cursos, seminarios, talleres para ampliar el conocimiento de los asociados.'),
    SizedBox(height: 5.0),
    Text('Plataforma digital para el Asociado, que facilitara conocer sobre sus cuotas pendientes de pagos, eventos de capacitación, eventos deportivos, culturales y otros., para lo cual se les asignara un pin.'),
    SizedBox(height: 5.0),
    Text('Foros virtuales y presenciales sobre temas técnicos.'),
    SizedBox(height: 5.0),
    Text('Deportes, Cultura y Recreación', style: TextStyle(color: Color(0xFF6ca125), fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('Incentivar la participación de los asociados en todas las ramas deportivas inicialmente a nivel departamental, para seleccionar a los asociados más destacados para que representen al CAULP en torneos inter profesionales, departamentales y nacionales.'),
    SizedBox(height: 5.0),
    Text('Propiciar actividades como; Clases de Zumba, Meditación, Carreras Deportivas, Torneos de ajedrez, Torneos de cacho, etc.'),
    SizedBox(height: 5.0),
    Text('Promover actividades culturales dentro de las instalaciones del CAULP.'),
    SizedBox(height: 5.0),
    Text('Promover actividades folklóricas y artísticas.'),
    SizedBox(height: 5.0),
    Text('Responsabilidad Social:', style: TextStyle(fontWeight: FontWeight.bold)),
    SizedBox(height: 5.0),
    Text('Como institución colegiada promover la responsabilidad social de los asociados al CAULP con diversas actividades en pro de la sociedad. Como Ferias de Promoción del CAULP como parte del Aniversario de Fundación.'),
    SizedBox(height: 5.0),
    Text('Como resultado de nuestra propuesta se lograra:'),
    SizedBox(height: 5.0),
    Text('1. Resultados y Eficiencia'),
    Text('2. Clima Laboral y compromiso'),
    Text('3. Cultura Digital'),
    Text('4. Satisfacción del Asociado')
  ];
}
